#!/usr/local/bin/node

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Libs
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
const http    = require('request-promise');
const gulp    = require('gulp');
const appkeys = require('./keys.json');

// TODO - GET/MAKE BLOCK labled "Open Growth"
// TODO - ...
// TODO - wait for BLOCK to boot
// TODO - test BLOCK
// TODO - show DEBUG output
// TODO - 
// TODO - print Signal cURLS and JS Functions for reporing a signal
// TODO - 

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Main
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
var $scope = {};

pubnub_login( appkeys.pubnub.email, appkeys.pubnub.password ).then( login => {

    // Logged into Global Admin Dashboard
    console.log( 'Logged In!', login.result.user_id );
    $scope.login = login.result;
    return build();

} ).then( result => {

    // Built Event Handler
    console.log( 'Built Event Handler!', result.length );
    $scope.code = result;
    return upload();

} ).then( result => {

    // Uploaded EH Code
    console.log( 'Uploaded!', result );
    return restart();

} ).then( result => {

    // Sent Restart Signal
    console.log( 'Restarting!', result );
    return instructions();

} ).then( result => {

    const pub = appkeys.pubnub.publish;
    const sub = appkeys.pubnub.subscribe;
    const chn = 'opengrowth.signals';
    const msg = '\\{"signal":"test","email":"stephen@pubnub.com"\\}';

    // Done Printing Instructions
    console.log(`
        ## Try it out!
        curl 'https://ps.pubnub.com/subscribe/${sub}/${chn}/0/-1' &
        curl 'https://ps.pubnub.com/publish/${pub}/${sub}/0/${chn}/0/${msg}'
        echo
    `);

} );

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Build Event Handler Code
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
function build() {
    var buffer = ''
    var keys   = 'opengrowth.keys = ' + JSON.stringify(appkeys) + ';'
    return new Promise( ( resolve, reject ) => {
        gulp.src(['./handlers/signals.js','./signals/*.js'])
        .on( 'end',   data  => { resolve(buffer + keys) } )
        .on( 'error', error => { reject(error)          } )
        .on( 'data',  bytes => {
            buffer += bytes.contents.toString().trim();
        } );
    } );
}

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Upload Event Handler Code
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
function upload() {
    return http({
        method  : 'PUT'
    ,   json    : true
    ,   uri     : 'https://admin.pubnub.com/api/v1' + 
                  '/blocks/key/226891/event_handler/2010'
    ,   headers : { 'X-Session-Token' : $scope.login.token }
    ,   body    : {
            key_id    : 226891
        ,   block_id  : 2071
        ,   id        : 2010
        ,   code      : $scope.code
        ,   channels  : "opengrowth.signals"
        ,   event     : "js-before-publish"
        ,   type      : "js"
        ,   log_level : "debug"
        ,   name      : "Open Growt Signalh Handler"
        ,   output    : "opengrowth.debug"
        }
    }).catch( error => {
        console.error( 'error', error );
    } );
}

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Print cURL Example
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
function instructions() {
    
}

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Restart Event Handler
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
function restart() {
//curl --data ''  \
    //-H 'Content-Type: application/json'                                   \
    return http({
        method  : 'POST'
    ,   uri     : 'https://admin.pubnub.com/api/v1' + 
                  '/blocks/key/226891/block/2071/start'
    ,   body    : { block_id : 2071, key_id : 226891, action : "start" }
    ,   headers : { 'X-Session-Token' : $scope.login.token }
    ,   json    : true
    }).catch( error => {
        console.error( 'error', error );
    } );
}

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Login to PubNub
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
function pubnub_login( email, password ) {
    return http({
        method : 'POST'
    ,   uri    : 'https://admin.pubnub.com/api/me'
    ,   body   : { 'email' : email, 'password' : password }
    ,   json   : true
    }).catch( error => {
        console.error( 'error', error );
    } );
}
